# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CM_GraphForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphForm(object):
    def setupUi(self, GraphForm):
        GraphForm.setObjectName("GraphForm")
        GraphForm.resize(400, 360)
        GraphForm.setMinimumSize(QtCore.QSize(400, 360))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(10)
        GraphForm.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/graph.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GraphForm.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(GraphForm)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(GraphForm)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(GraphForm)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 45))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 45))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(61, 16))
        self.label.setMaximumSize(QtCore.QSize(61, 16))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setMinimumSize(QtCore.QSize(91, 23))
        self.pushButton.setMaximumSize(QtCore.QSize(91, 23))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/paint.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox.raise_()
        self.widget.raise_()

        self.retranslateUi(GraphForm)
        QtCore.QMetaObject.connectSlotsByName(GraphForm)

    def retranslateUi(self, GraphForm):
        _translate = QtCore.QCoreApplication.translate
        GraphForm.setWindowTitle(_translate("GraphForm", "Граф"))
        self.label.setText(_translate("GraphForm", "Тип графа"))
        self.comboBox.setItemText(0, _translate("GraphForm", "Круговой"))
        self.comboBox.setItemText(1, _translate("GraphForm", "Спиральный"))
        self.comboBox.setItemText(2, _translate("GraphForm", "Случайный"))
        self.comboBox.setItemText(3, _translate("GraphForm", "Планарный"))
        self.pushButton.setText(_translate("GraphForm", "Отобразить"))
import forms_resources_rc
