# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CM_ImitationForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImitationForm(object):
    def setupUi(self, ImitationForm):
        ImitationForm.setObjectName("ImitationForm")
        ImitationForm.resize(620, 500)
        ImitationForm.setMinimumSize(QtCore.QSize(620, 500))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(10)
        ImitationForm.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/imitation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ImitationForm.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(ImitationForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(ImitationForm)
        self.textBrowser.setMinimumSize(QtCore.QSize(601, 131))
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 131))
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.tableView = QtWidgets.QTableView(ImitationForm)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(ImitationForm)
        self.label.setMinimumSize(QtCore.QSize(91, 16))
        self.label.setMaximumSize(QtCore.QSize(91, 16))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(ImitationForm)
        self.spinBox.setMinimumSize(QtCore.QSize(90, 23))
        self.spinBox.setMinimum(10)
        self.spinBox.setMaximum(10000)
        self.spinBox.setProperty("value", 100)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnCreate = QtWidgets.QPushButton(ImitationForm)
        self.btnCreate.setMinimumSize(QtCore.QSize(75, 23))
        self.btnCreate.setMaximumSize(QtCore.QSize(75, 23))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/btn_ok_200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCreate.setIcon(icon1)
        self.btnCreate.setObjectName("btnCreate")
        self.horizontalLayout.addWidget(self.btnCreate)
        self.btnSave = QtWidgets.QPushButton(ImitationForm)
        self.btnSave.setEnabled(False)
        self.btnSave.setMinimumSize(QtCore.QSize(91, 23))
        self.btnSave.setMaximumSize(QtCore.QSize(91, 23))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSave.setIcon(icon2)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ImitationForm)
        QtCore.QMetaObject.connectSlotsByName(ImitationForm)

    def retranslateUi(self, ImitationForm):
        _translate = QtCore.QCoreApplication.translate
        ImitationForm.setWindowTitle(_translate("ImitationForm", "Создание имитационных данных"))
        self.textBrowser.setHtml(_translate("ImitationForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Franklin Gothic Medium\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/icons/help.png\" width=\"15\" height=\"16\" style=\"vertical-align: top;\" />Имитационные данные - это искусственные данные, которые используют при отсутствии данных наблюдений с объекта управления. При их формировании используется множество допущений - нормальность распределения факторов, наличие латентных количественных факторов в основе качественных факторов, линейность связей в модели, отсутствие иных факторов в модели. Однако эти данных можно применять для тестирования некоторых алгоритмов или в иных обучающих целях.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Позволяет работать с факторами <span style=\" text-decoration: underline;\">любых шкал</span>.</p></body></html>"))
        self.label.setText(_translate("ImitationForm", "Объем данных"))
        self.btnCreate.setText(_translate("ImitationForm", "Создать"))
        self.btnSave.setText(_translate("ImitationForm", "Сохранить"))
import forms_resources_rc
