# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CM_ProcessForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProcessForm(object):
    def setupUi(self, ProcessForm):
        ProcessForm.setObjectName("ProcessForm")
        ProcessForm.resize(620, 500)
        ProcessForm.setMinimumSize(QtCore.QSize(620, 500))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(10)
        ProcessForm.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/process.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ProcessForm.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProcessForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(ProcessForm)
        self.textBrowser.setMinimumSize(QtCore.QSize(601, 131))
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 131))
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.tableWidget = QtWidgets.QTableWidget(ProcessForm)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 90))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 90))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.tableView = QtWidgets.QTableView(ProcessForm)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCreate = QtWidgets.QPushButton(ProcessForm)
        self.btnCreate.setMinimumSize(QtCore.QSize(75, 23))
        self.btnCreate.setMaximumSize(QtCore.QSize(75, 23))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/btn_ok_200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCreate.setIcon(icon1)
        self.btnCreate.setObjectName("btnCreate")
        self.horizontalLayout.addWidget(self.btnCreate)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnPlot = QtWidgets.QPushButton(ProcessForm)
        self.btnPlot.setEnabled(False)
        self.btnPlot.setMinimumSize(QtCore.QSize(75, 23))
        self.btnPlot.setMaximumSize(QtCore.QSize(75, 23))
        self.btnPlot.setIcon(icon)
        self.btnPlot.setObjectName("btnPlot")
        self.horizontalLayout.addWidget(self.btnPlot)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnSave = QtWidgets.QPushButton(ProcessForm)
        self.btnSave.setEnabled(False)
        self.btnSave.setMinimumSize(QtCore.QSize(91, 23))
        self.btnSave.setMaximumSize(QtCore.QSize(91, 23))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSave.setIcon(icon2)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ProcessForm)
        QtCore.QMetaObject.connectSlotsByName(ProcessForm)

    def retranslateUi(self, ProcessForm):
        _translate = QtCore.QCoreApplication.translate
        ProcessForm.setWindowTitle(_translate("ProcessForm", "Оценка переходного процесса"))
        self.textBrowser.setHtml(_translate("ProcessForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Franklin Gothic Medium\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/icons/help.png\" width=\"15\" height=\"16\" style=\"vertical-align: top;\" /><span style=\" vertical-align:top;\">Переходной процесс</span> - изменения во времени координат динамической системы, до некоторого установившегося состояния; возникает под влиянием возмущающих воздействий, а также вследствие ненулевых начальных условий. В случае когнитивных моделей - это значения факторов, изменяющихся на каждом такте. Такт - нефиксированное время, необходимое для передачи воздействия от одного фактора к другому посредством их связи.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Позволяет работать <span style=\" text-decoration: underline;\">только с количественными факторами</span>.</p></body></html>"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("ProcessForm", "Шаг 0"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("ProcessForm", "Шаг 1"))
        self.btnCreate.setText(_translate("ProcessForm", "Создать"))
        self.btnPlot.setText(_translate("ProcessForm", "График"))
        self.btnSave.setText(_translate("ProcessForm", "Сохранить"))
import forms_resources_rc
