# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CM_TableForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TableForm(object):
    def setupUi(self, TableForm):
        TableForm.setObjectName("TableForm")
        TableForm.resize(400, 300)
        TableForm.setMinimumSize(QtCore.QSize(400, 300))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(10)
        TableForm.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/table.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TableForm.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(TableForm)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(TableForm)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)

        self.retranslateUi(TableForm)
        QtCore.QMetaObject.connectSlotsByName(TableForm)

    def retranslateUi(self, TableForm):
        _translate = QtCore.QCoreApplication.translate
        TableForm.setWindowTitle(_translate("TableForm", "Табличный вид"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TableForm", "Имя фактора"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TableForm", "Шкала"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TableForm", "Роль"))
import forms_resources_rc
